name: SpringBoot AWS Auto Deploy

on:
  push:
    branches: [ main ]  # 你本地是main分支，就写main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取GitHub代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置JDK17 你是其他版本改数字就行
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3. Maven编译打包 跳过测试
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. 配置SSH连接AWS
      - name: SSH setup
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      # 5. 自动上传Jar到AWS + 重启SpringBoot
      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.AWS_HOST }}
          USER: ${{ secrets.AWS_USER }}
        run: |
          # 上传target下的jar到AWS指定目录 改成你服务器真实路径
          scp -o StrictHostKeyChecking=no target/*.jar ${USER}@${HOST}:/home/boot/
          
          # 远程执行命令：停旧项目、启新项目
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
            # 找到正在运行的java进程并杀掉
            ps -ef | grep java | grep jar | awk '{print $2}' | xargs kill -9 2>/dev/null
            # 后台启动新jar 改成你的端口和日志路径
            nohup java -jar /home/boot/*.jar --server.port=8080 > /home/boot/app.log 2>&1 &
          EOF
